-- Staff leave requests
CREATE TABLE IF NOT EXISTS staff_leave_requests (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id     UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  user_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  leave_type    TEXT NOT NULL CHECK (leave_type IN ('sick', 'casual', 'earned', 'unpaid', 'other')),
  from_date     DATE NOT NULL,
  to_date       DATE NOT NULL,
  days          INT NOT NULL GENERATED ALWAYS AS (to_date - from_date + 1) STORED,
  reason        TEXT,
  status        TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_by   UUID REFERENCES users(id),
  reviewed_at   TIMESTAMPTZ,
  review_note   TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_leave_requests_school ON staff_leave_requests(school_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_user   ON staff_leave_requests(user_id);

-- Offer letters (generated by admin/principal, signed by staff)
CREATE TABLE IF NOT EXISTS staff_offer_letters (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id         UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  user_id           UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role              TEXT NOT NULL,
  start_date        DATE NOT NULL,
  gross_salary      NUMERIC(12,2) NOT NULL,
  components        JSONB NOT NULL DEFAULT '[]',
  employment_terms  TEXT,
  pdf_url           TEXT,
  status            TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'signed', 'declined')),
  signed_at         TIMESTAMPTZ,
  created_by        UUID REFERENCES users(id),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_offer_letters_school ON staff_offer_letters(school_id);
CREATE INDEX IF NOT EXISTS idx_offer_letters_user   ON staff_offer_letters(user_id);
