/**
 * pdf/base.ts — Shared PDFKit primitives
 *
 * All internal helpers and shared interfaces used by every PDF generator.
 * Nothing in this file is document-specific.
 */

import PDFDocument from 'pdfkit';

// ---------------------------------------------------------------------------
// Shared context interfaces
// ---------------------------------------------------------------------------

export interface BrandingContext {
  school_name: string;
  school_address: string;
  logo_url: string | null;
  letterhead_url?: string | null;
  principal_signature_url?: string | null;
  principal_designation?: string | null;
}

export interface GeneratorContext {
  generated_by_name: string;
  generated_by_role: string;
  generated_at: Date;
}

// ---------------------------------------------------------------------------
// Layout constants
// ---------------------------------------------------------------------------

export const MARGIN = 50;
export const PAGE_WIDTH = 595.28; // A4 width in points
export const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

// ---------------------------------------------------------------------------
// Internal helpers (exported for use by sibling modules)
// ---------------------------------------------------------------------------

/** Collect all pdfkit chunks into a single Buffer via a Promise. */
export function collectBuffer(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}

/**
 * Add a branded header to the current page position.
 * When `logoBuffer` is provided the logo image is embedded at the top;
 * otherwise the school name is rendered as bold text.
 */
export function addBrandedHeader(
  doc: PDFKit.PDFDocument,
  branding: BrandingContext,
  reportTitle?: string,
  logoBuffer?: Buffer | null,
): void {
  const startY = doc.y;

  if (logoBuffer) {
    const logoX = MARGIN + (CONTENT_WIDTH - 120) / 2;
    doc.image(logoBuffer, logoX, startY, { fit: [120, 80], align: 'center' });
    doc.y = startY + 88;
  } else {
    doc
      .font('Helvetica-Bold')
      .fontSize(16)
      .text(branding.school_name, MARGIN, startY, { align: 'center', width: CONTENT_WIDTH });
  }

  doc
    .font('Helvetica')
    .fontSize(10)
    .fillColor('#666666')
    .text(branding.school_address, MARGIN, doc.y + 2, { align: 'center', width: CONTENT_WIDTH });

  if (reportTitle) {
    doc
      .font('Helvetica-Bold')
      .fontSize(12)
      .fillColor('#000000')
      .text(reportTitle, MARGIN, doc.y + 4, { align: 'center', width: CONTENT_WIDTH });
  }

  doc.fillColor('#000000');

  const ruleY = doc.y + 6;
  doc
    .moveTo(MARGIN, ruleY)
    .lineTo(PAGE_WIDTH - MARGIN, ruleY)
    .strokeColor('#cccccc')
    .lineWidth(1)
    .stroke();

  doc.strokeColor('#000000').lineWidth(1);
  doc.moveDown(0.5);
}

/**
 * Register a per-page footer showing generator name, role, page number, and date.
 */
export function registerFooter(
  doc: PDFKit.PDFDocument,
  ctx: GeneratorContext,
): void {
  const dateStr = ctx.generated_at.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });

  let pageNumber = 0;

  doc.on('pageAdded', () => {
    pageNumber++;
    const footerY = doc.page.height - 40;
    const footerText = `Generated by ${ctx.generated_by_name} (${ctx.generated_by_role}) | Page ${pageNumber} | Generated on ${dateStr}`;

    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor('#888888')
      .text(footerText, MARGIN, footerY, { align: 'center', width: CONTENT_WIDTH });

    doc.fillColor('#000000');
  });
}

/** Draw a simple two-column key-value row. */
export function addKeyValue(
  doc: PDFKit.PDFDocument,
  label: string,
  value: string,
  y?: number,
): void {
  const rowY = y ?? doc.y;
  doc
    .font('Helvetica-Bold')
    .fontSize(10)
    .text(label + ':', MARGIN, rowY, { continued: false, width: 160 });
  doc
    .font('Helvetica')
    .fontSize(10)
    .text(value, MARGIN + 170, rowY, { width: CONTENT_WIDTH - 170 });
}

/** Draw a simple table with headers and rows. */
export function addTable(
  doc: PDFKit.PDFDocument,
  headers: string[],
  rows: string[][],
  colWidths?: number[],
): void {
  const defaultColWidth = CONTENT_WIDTH / headers.length;
  const widths = colWidths ?? headers.map(() => defaultColWidth);

  const rowHeight = 20;
  let x = MARGIN;
  let y = doc.y + 4;

  // Header row background
  doc.rect(MARGIN, y, CONTENT_WIDTH, rowHeight).fill('#f0f0f0');
  doc.fillColor('#000000');

  headers.forEach((header, i) => {
    doc
      .font('Helvetica-Bold')
      .fontSize(9)
      .text(header, x + 4, y + 5, { width: widths[i] - 8, lineBreak: false });
    x += widths[i];
  });

  y += rowHeight;

  rows.forEach((row, rowIdx) => {
    if (rowIdx % 2 === 1) {
      doc.rect(MARGIN, y, CONTENT_WIDTH, rowHeight).fill('#fafafa');
      doc.fillColor('#000000');
    }

    x = MARGIN;
    row.forEach((cell, i) => {
      doc
        .font('Helvetica')
        .fontSize(9)
        .text(cell, x + 4, y + 5, { width: widths[i] - 8, lineBreak: false });
      x += widths[i];
    });

    y += rowHeight;

    if (y > doc.page.height - 80) {
      doc.addPage();
      y = doc.y;
    }
  });

  doc.y = y + 4;
}
