import PDFDocument from 'pdfkit';

// ---------------------------------------------------------------------------
// Shared context interfaces
// ---------------------------------------------------------------------------

export interface BrandingContext {
  school_name: string;
  school_address: string;
  logo_url: string | null; // null → use school name as text header
}

export interface GeneratorContext {
  generated_by_name: string;
  generated_by_role: string;
  generated_at: Date;
}

// ---------------------------------------------------------------------------
// Per-document data interfaces
// ---------------------------------------------------------------------------

export interface ReceiptData {
  receipt_number: string;
  student_name: string;
  class_name: string;
  fee_head_breakdown: { name: string; amount: number }[];
  amount_paid: number;
  payment_mode: string;
  payment_date: Date;
  school_name: string;
}

export interface PayslipData {
  staff_name: string;
  role: string;
  employee_id: string;
  month_year: string;
  working_days: number;
  present_days: number;
  absent_days: number;
  leave_days: number;
  gross_salary: number;
  per_day_rate: number;
  components: { name: string; amount: number }[];
  deductions: { name: string; amount: number }[];
  net_salary: number;
  payment_mode: string;
  payment_date: Date;
}

export interface ReportData {
  title: string;
  date_range: string;
  headers: string[];
  rows: string[][];
  summary: Record<string, string>;
}

export interface OfferLetterData {
  staff_name: string;
  role: string;
  start_date: Date;
  salary_breakdown: { component: string; amount: number }[];
  employment_terms: string;
  school_name: string;
}

export interface ExperienceLetterData {
  staff_name: string;
  role: string;
  start_date: Date;
  end_date: Date;
  school_name: string;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** Collect all pdfkit chunks into a single Buffer via a Promise. */
function collectBuffer(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}

const MARGIN = 50;
const PAGE_WIDTH = 595.28; // A4 width in points
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

/**
 * Add a branded header to the current page position.
 * TODO: Add logo rendering once logo_url is a reliable local/CDN path.
 *       Currently skipped because logo_url may be a remote URL that requires
 *       async fetching; use school name as text header instead.
 */
function addBrandedHeader(
  doc: PDFKit.PDFDocument,
  branding: BrandingContext,
  reportTitle?: string,
): void {
  const startY = doc.y;

  // School name — bold, 16pt, centered
  doc
    .font('Helvetica-Bold')
    .fontSize(16)
    .text(branding.school_name, MARGIN, startY, { align: 'center', width: CONTENT_WIDTH });

  // School address — 10pt, gray, centered
  doc
    .font('Helvetica')
    .fontSize(10)
    .fillColor('#666666')
    .text(branding.school_address, MARGIN, doc.y + 2, { align: 'center', width: CONTENT_WIDTH });

  // Optional report title
  if (reportTitle) {
    doc
      .font('Helvetica-Bold')
      .fontSize(12)
      .fillColor('#000000')
      .text(reportTitle, MARGIN, doc.y + 4, { align: 'center', width: CONTENT_WIDTH });
  }

  // Reset fill color
  doc.fillColor('#000000');

  // Horizontal rule
  const ruleY = doc.y + 6;
  doc
    .moveTo(MARGIN, ruleY)
    .lineTo(PAGE_WIDTH - MARGIN, ruleY)
    .strokeColor('#cccccc')
    .lineWidth(1)
    .stroke();

  doc.strokeColor('#000000').lineWidth(1);
  doc.moveDown(0.5);
}

/**
 * Register a footer on every page that shows:
 * "Generated by [name] ([role]) | Page X of Y | Generated on [date]"
 *
 * pdfkit does not natively support "Page X of Y" without a two-pass render,
 * so we use a range object and update it after all pages are added.
 */
function registerFooter(
  doc: PDFKit.PDFDocument,
  ctx: GeneratorContext,
): void {
  const dateStr = ctx.generated_at.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });

  let pageNumber = 0;

  doc.on('pageAdded', () => {
    pageNumber++;
    // We write the footer at the bottom of each page as it is added.
    // "Page X of Y" — total pages unknown at this point, so we write "Page X"
    // and append "of Y" in the finalise step via the bufferedPageRange trick.
    const footerY = doc.page.height - 40;
    const footerText = `Generated by ${ctx.generated_by_name} (${ctx.generated_by_role}) | Page ${pageNumber} | Generated on ${dateStr}`;

    doc
      .font('Helvetica')
      .fontSize(8)
      .fillColor('#888888')
      .text(footerText, MARGIN, footerY, { align: 'center', width: CONTENT_WIDTH });

    doc.fillColor('#000000');
  });
}

/** Draw a simple two-column key-value row. */
function addKeyValue(
  doc: PDFKit.PDFDocument,
  label: string,
  value: string,
  y?: number,
): void {
  const rowY = y ?? doc.y;
  doc
    .font('Helvetica-Bold')
    .fontSize(10)
    .text(label + ':', MARGIN, rowY, { continued: false, width: 160 });
  doc
    .font('Helvetica')
    .fontSize(10)
    .text(value, MARGIN + 170, rowY, { width: CONTENT_WIDTH - 170 });
}

/** Draw a simple table with headers and rows. */
function addTable(
  doc: PDFKit.PDFDocument,
  headers: string[],
  rows: string[][],
  colWidths?: number[],
): void {
  const defaultColWidth = CONTENT_WIDTH / headers.length;
  const widths = colWidths ?? headers.map(() => defaultColWidth);

  const rowHeight = 20;
  let x = MARGIN;
  let y = doc.y + 4;

  // Header row background
  doc.rect(MARGIN, y, CONTENT_WIDTH, rowHeight).fill('#f0f0f0');
  doc.fillColor('#000000');

  headers.forEach((header, i) => {
    doc
      .font('Helvetica-Bold')
      .fontSize(9)
      .text(header, x + 4, y + 5, { width: widths[i] - 8, lineBreak: false });
    x += widths[i];
  });

  y += rowHeight;

  rows.forEach((row, rowIdx) => {
    // Alternate row shading
    if (rowIdx % 2 === 1) {
      doc.rect(MARGIN, y, CONTENT_WIDTH, rowHeight).fill('#fafafa');
      doc.fillColor('#000000');
    }

    x = MARGIN;
    row.forEach((cell, i) => {
      doc
        .font('Helvetica')
        .fontSize(9)
        .text(cell, x + 4, y + 5, { width: widths[i] - 8, lineBreak: false });
      x += widths[i];
    });

    y += rowHeight;

    // Add a new page if we're running out of space
    if (y > doc.page.height - 80) {
      doc.addPage();
      y = doc.y;
    }
  });

  doc.y = y + 4;
}

// ---------------------------------------------------------------------------
// Public PDF generators
// ---------------------------------------------------------------------------

/**
 * Generate a fee payment receipt PDF.
 */
export async function generateReceiptPDF(
  data: ReceiptData,
  branding: BrandingContext,
  ctx: GeneratorContext,
): Promise<Buffer> {
  const doc = new PDFDocument({ margin: MARGIN, size: 'A4', bufferPages: true });
  const bufferPromise = collectBuffer(doc);

  registerFooter(doc, ctx);
  addBrandedHeader(doc, branding, 'Fee Payment Receipt');

  doc.moveDown(0.5);

  // Receipt meta
  addKeyValue(doc, 'Receipt No.', data.receipt_number);
  doc.moveDown(0.3);
  addKeyValue(doc, 'Student Name', data.student_name);
  doc.moveDown(0.3);
  addKeyValue(doc, 'Class', data.class_name);
  doc.moveDown(0.3);
  addKeyValue(
    doc,
    'Payment Date',
    data.payment_date.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
  );
  doc.moveDown(0.3);
  addKeyValue(doc, 'Payment Mode', data.payment_mode);
  doc.moveDown(0.8);

  // Fee head breakdown table
  doc.font('Helvetica-Bold').fontSize(11).text('Fee Breakdown', MARGIN, doc.y);
  doc.moveDown(0.3);

  const breakdownRows = data.fee_head_breakdown.map((fh) => [
    fh.name,
    `₹ ${fh.amount.toFixed(2)}`,
  ]);
  addTable(doc, ['Fee Head', 'Amount'], breakdownRows, [CONTENT_WIDTH * 0.7, CONTENT_WIDTH * 0.3]);

  // Total
  doc.moveDown(0.3);
  doc
    .font('Helvetica-Bold')
    .fontSize(11)
    .text(`Total Amount Paid: ₹ ${data.amount_paid.toFixed(2)}`, MARGIN, doc.y, {
      align: 'right',
      width: CONTENT_WIDTH,
    });

  doc.moveDown(1);

  // Non-refundable notice — red italic
  doc
    .font('Helvetica-Oblique')
    .fontSize(9)
    .fillColor('#cc0000')
    .text(
      'Please note: Fees once paid cannot be refunded under any circumstances.',
      MARGIN,
      doc.y,
      { align: 'center', width: CONTENT_WIDTH },
    );

  doc.fillColor('#000000');

  doc.end();
  return bufferPromise;
}

/**
 * Generate a staff salary payslip PDF.
 */
export async function generatePayslipPDF(
  data: PayslipData,
  branding: BrandingContext,
  ctx: GeneratorContext,
): Promise<Buffer> {
  const doc = new PDFDocument({ margin: MARGIN, size: 'A4', bufferPages: true });
  const bufferPromise = collectBuffer(doc);

  registerFooter(doc, ctx);
  addBrandedHeader(doc, branding, 'Salary Payslip');

  doc.moveDown(0.5);

  // Staff details table
  doc.font('Helvetica-Bold').fontSize(11).text('Staff Details', MARGIN, doc.y);
  doc.moveDown(0.3);
  addTable(
    doc,
    ['Name', 'Role', 'Employee ID', 'Month / Year'],
    [[data.staff_name, data.role, data.employee_id, data.month_year]],
    [
      CONTENT_WIDTH * 0.3,
      CONTENT_WIDTH * 0.2,
      CONTENT_WIDTH * 0.2,
      CONTENT_WIDTH * 0.3,
    ],
  );

  doc.moveDown(0.5);

  // Attendance summary
  doc.font('Helvetica-Bold').fontSize(11).text('Attendance Summary', MARGIN, doc.y);
  doc.moveDown(0.3);
  addTable(
    doc,
    ['Working Days', 'Present', 'Absent', 'Leaves'],
    [
      [
        String(data.working_days),
        String(data.present_days),
        String(data.absent_days),
        String(data.leave_days),
      ],
    ],
    [
      CONTENT_WIDTH * 0.25,
      CONTENT_WIDTH * 0.25,
      CONTENT_WIDTH * 0.25,
      CONTENT_WIDTH * 0.25,
    ],
  );

  doc.moveDown(0.5);

  // Earnings table
  doc.font('Helvetica-Bold').fontSize(11).text('Earnings', MARGIN, doc.y);
  doc.moveDown(0.3);
  const earningsRows = data.components.map((c) => [c.name, `₹ ${c.amount.toFixed(2)}`]);
  earningsRows.push(['Gross Total', `₹ ${data.gross_salary.toFixed(2)}`]);
  addTable(doc, ['Component', 'Amount'], earningsRows, [CONTENT_WIDTH * 0.7, CONTENT_WIDTH * 0.3]);

  doc.moveDown(0.5);

  // Deductions table
  doc.font('Helvetica-Bold').fontSize(11).text('Deductions', MARGIN, doc.y);
  doc.moveDown(0.3);
  const totalDeductions = data.deductions.reduce((sum, d) => sum + d.amount, 0);
  const deductionRows = data.deductions.map((d) => [d.name, `₹ ${d.amount.toFixed(2)}`]);
  deductionRows.push(['Total Deductions', `₹ ${totalDeductions.toFixed(2)}`]);
  addTable(doc, ['Deduction', 'Amount'], deductionRows, [CONTENT_WIDTH * 0.7, CONTENT_WIDTH * 0.3]);

  doc.moveDown(0.5);

  // Net salary — highlighted box
  const netY = doc.y;
  doc.rect(MARGIN, netY, CONTENT_WIDTH, 28).fill('#e8f5e9');
  doc.fillColor('#000000');
  doc
    .font('Helvetica-Bold')
    .fontSize(13)
    .text(`Net Salary: ₹ ${data.net_salary.toFixed(2)}`, MARGIN + 8, netY + 7, {
      width: CONTENT_WIDTH - 16,
      align: 'right',
    });

  doc.y = netY + 36;
  doc.moveDown(0.5);

  // Payment details
  doc.font('Helvetica-Bold').fontSize(11).text('Payment Details', MARGIN, doc.y);
  doc.moveDown(0.3);
  addKeyValue(doc, 'Payment Mode', data.payment_mode);
  doc.moveDown(0.3);
  addKeyValue(
    doc,
    'Payment Date',
    data.payment_date.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
  );

  doc.moveDown(1);

  // Disclaimer
  doc
    .font('Helvetica-Oblique')
    .fontSize(9)
    .fillColor('#555555')
    .text('This is a system-generated salary slip.', MARGIN, doc.y, {
      align: 'center',
      width: CONTENT_WIDTH,
    });

  doc.fillColor('#000000');

  doc.end();
  return bufferPromise;
}

/**
 * Generate a financial report PDF.
 */
export async function generateReportPDF(
  data: ReportData,
  branding: BrandingContext,
  ctx: GeneratorContext,
): Promise<Buffer> {
  const doc = new PDFDocument({ margin: MARGIN, size: 'A4', bufferPages: true });
  const bufferPromise = collectBuffer(doc);

  registerFooter(doc, ctx);
  addBrandedHeader(doc, branding, data.title);

  doc.moveDown(0.3);

  // Date range
  doc
    .font('Helvetica')
    .fontSize(10)
    .fillColor('#444444')
    .text(`Period: ${data.date_range}`, MARGIN, doc.y, { align: 'center', width: CONTENT_WIDTH });
  doc.fillColor('#000000');

  doc.moveDown(0.8);

  // Data table
  addTable(doc, data.headers, data.rows);

  doc.moveDown(0.8);

  // Summary section
  if (Object.keys(data.summary).length > 0) {
    doc.font('Helvetica-Bold').fontSize(11).text('Summary', MARGIN, doc.y);
    doc.moveDown(0.3);

    Object.entries(data.summary).forEach(([key, value]) => {
      addKeyValue(doc, key, value);
      doc.moveDown(0.3);
    });
  }

  doc.end();
  return bufferPromise;
}

/**
 * Generate an offer letter PDF.
 */
export async function generateOfferLetterPDF(
  data: OfferLetterData,
  branding: BrandingContext,
  ctx: GeneratorContext,
): Promise<Buffer> {
  const doc = new PDFDocument({ margin: MARGIN, size: 'A4', bufferPages: true });
  const bufferPromise = collectBuffer(doc);

  registerFooter(doc, ctx);
  addBrandedHeader(doc, branding, 'Offer Letter');

  doc.moveDown(0.8);

  const startDateStr = data.start_date.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });

  // Salutation
  doc
    .font('Helvetica')
    .fontSize(11)
    .text(`Dear ${data.staff_name},`, MARGIN, doc.y);

  doc.moveDown(0.5);

  doc.text(
    `We are pleased to offer you the position of ${data.role} at ${data.school_name}, ` +
      `effective from ${startDateStr}. Please find the details of your offer below.`,
    MARGIN,
    doc.y,
    { width: CONTENT_WIDTH },
  );

  doc.moveDown(0.8);

  // Salary breakdown table
  doc.font('Helvetica-Bold').fontSize(11).text('Compensation Breakdown', MARGIN, doc.y);
  doc.moveDown(0.3);

  const salaryRows = data.salary_breakdown.map((s) => [s.component, `₹ ${s.amount.toFixed(2)}`]);
  addTable(doc, ['Component', 'Amount (per month)'], salaryRows, [
    CONTENT_WIDTH * 0.65,
    CONTENT_WIDTH * 0.35,
  ]);

  doc.moveDown(0.8);

  // Employment terms
  doc.font('Helvetica-Bold').fontSize(11).text('Terms and Conditions', MARGIN, doc.y);
  doc.moveDown(0.3);
  doc
    .font('Helvetica')
    .fontSize(10)
    .text(data.employment_terms, MARGIN, doc.y, { width: CONTENT_WIDTH });

  doc.moveDown(1.5);

  // Signature block
  doc.font('Helvetica').fontSize(10).text('Authorised Signatory', MARGIN, doc.y);
  doc.text(data.school_name, MARGIN, doc.y + 2);

  doc.end();
  return bufferPromise;
}

/**
 * Generate an experience letter PDF.
 */
export async function generateExperienceLetterPDF(
  data: ExperienceLetterData,
  branding: BrandingContext,
  ctx: GeneratorContext,
): Promise<Buffer> {
  const doc = new PDFDocument({ margin: MARGIN, size: 'A4', bufferPages: true });
  const bufferPromise = collectBuffer(doc);

  registerFooter(doc, ctx);
  addBrandedHeader(doc, branding, 'Experience Letter');

  doc.moveDown(0.8);

  const startDateStr = data.start_date.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });
  const endDateStr = data.end_date.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });
  const issueDateStr = ctx.generated_at.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });

  // Date
  doc
    .font('Helvetica')
    .fontSize(10)
    .fillColor('#444444')
    .text(`Date: ${issueDateStr}`, MARGIN, doc.y, { align: 'right', width: CONTENT_WIDTH });
  doc.fillColor('#000000');

  doc.moveDown(0.5);

  // Salutation
  doc.font('Helvetica').fontSize(11).text(`To Whom It May Concern,`, MARGIN, doc.y);

  doc.moveDown(0.5);

  // Body
  doc.text(
    `This is to certify that ${data.staff_name} was employed with ${data.school_name} ` +
      `as ${data.role} from ${startDateStr} to ${endDateStr}.`,
    MARGIN,
    doc.y,
    { width: CONTENT_WIDTH },
  );

  doc.moveDown(0.5);

  doc.text(
    `During their tenure, ${data.staff_name} demonstrated professionalism and dedication. ` +
      `We wish them the very best in their future endeavours.`,
    MARGIN,
    doc.y,
    { width: CONTENT_WIDTH },
  );

  doc.moveDown(1.5);

  // Signature block
  doc.font('Helvetica').fontSize(10).text('Authorised Signatory', MARGIN, doc.y);
  doc.text(data.school_name, MARGIN, doc.y + 2);

  doc.end();
  return bufferPromise;
}
